### ISSUE TITLE
Serious security problems fixed in Enigmail 1.9.9

### ISSUE THREAD

**Issue by HulaHoopWhonix** [annealmail/annealmail#12]
Hi I understand you aren't actively maintaining annealmail at the moment. I just wanted to let you know (and also other users) that some major sec vulnerabilities that break security completely have been discovered in Enigmail last December and that they apply to annealmail by virtue of being based on it - until rebasing on the fixed version 1.9.9

For more info see:

https://enigmail.net/download/other/Enigmail%20Pentest%20Report%20by%20Cure53%20-%20Excerpt.pdf

https://posteo.de/en/blog/security-warning-for-thunderbird-users-and-enigmail-users-vulnerabilities-threaten-confidentiality-of-communication

cc/ @adrelanos

**Comment by mapmeld** [comment]
I've added a warning and archived the repo
